name: ci
on:
  push:
    branches: [main]
  pull_request:
permissions: read-all
jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.3
      - name: Remove lockfile if exists
        run: rm -f deno.lock
      - name: Check formatting
        run: deno fmt --check
      - name: Check linting
        run: deno lint
      - name: Check types
        run: deno check **/*.ts
      - name: Run tests
        run: deno test -A
      - name: Run tests with coverage
        run: deno test -A --coverage=coverage
      - name: Generate coverage report
        run: deno coverage coverage --lcov --output=coverage.lcov

  bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run tests
        run: bun test
