name: ci
on:
  push:
    branches: [main]
  pull_request:
permissions: read-all
jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Check formatting
        run: deno fmt --check
      - name: Check linting
        run: deno lint
      - name: Check types
        run: deno check **/*.ts
      - name: Run tests
        run: deno test -A
      - name: Run tests with coverage
        run: deno test -A --coverage=coverage
      - name: Generate coverage report
        run: deno coverage coverage --lcov --output=coverage.lcov
